-- MySQL Script generated by MySQL Workbench
-- Thu Nov  2 20:57:36 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema store
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema store
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `store` DEFAULT CHARACTER SET utf8 ;
USE `store` ;

-- -----------------------------------------------------
-- Table `store`.`Account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `store`.`Account` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `address` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `store`.`account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `store`.`account` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` NVARCHAR(45) NULL,
  `password` CHAR(32) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `store`.`Category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `store`.`Category` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` NVARCHAR(20) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `store`.`Product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `store`.`Product` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` NVARCHAR(45) NULL,
  `price` DECIMAL(20) NULL,
  `info` VARCHAR(45) NULL,
  `quantity` INT NULL,
  `salesNum` INT NULL,
  `pic` NVARCHAR(45) NULL,
  `category_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_category_idx_idx` (`category_id` ASC),
  CONSTRAINT `fk_category_idx`
    FOREIGN KEY (`category_id`)
    REFERENCES `store`.`Category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `store`.`cart`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `store`.`cart` (
  `account_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  `quantity` INT NULL DEFAULT 1,
  PRIMARY KEY (`account_id`, `product_id`),
  INDEX `fk_cart_product_idx` (`product_id` ASC),
  CONSTRAINT `fk_Cart_account`
    FOREIGN KEY (`account_id`)
    REFERENCES `store`.`account` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cart_product`
    FOREIGN KEY (`product_id`)
    REFERENCES `store`.`Product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `store`.`Order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `store`.`Order` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `account_id` INT NOT NULL,
  `time` DATETIME NOT NULL DEFAULT now(),
  `total` DECIMAL NOT NULL,
  `province` VARCHAR(45) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `street` NVARCHAR(45) NOT NULL,
  `phone` NVARCHAR(45) NOT NULL,
  `name` CHAR(11) NOT NULL,
  `state` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_order_account_idx` (`account_id` ASC),
  CONSTRAINT `fk_order_account`
    FOREIGN KEY (`account_id`)
    REFERENCES `store`.`account` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `store`.`address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `store`.`address` (
  `account_id` INT NOT NULL,
  `province` NVARCHAR(45) NULL,
  `city` NVARCHAR(45) NULL,
  `street` NVARCHAR(45) NULL,
  `name` VARCHAR(45) NULL,
  `phone` CHAR(11) NULL,
  `id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_account`
    FOREIGN KEY (`account_id`)
    REFERENCES `store`.`account` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `store`.`items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `store`.`items` (
  `order_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  `quantity` INT NULL,
  `num` INT NULL,
  `total` DECIMAL NULL,
  PRIMARY KEY (`order_id`, `product_id`),
  INDEX `fk_item_product_idx` (`product_id` ASC),
  CONSTRAINT `fk_item_order`
    FOREIGN KEY (`order_id`)
    REFERENCES `store`.`Order` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_item_product`
    FOREIGN KEY (`product_id`)
    REFERENCES `store`.`Product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

create view v_products as select id,title,price,quantity,salesNum,concat('.',pic) picPath from Product order by title;